Decouple `aws-sdk-rust` release from `smithy-rs` release (#1495)
* Remove smoketest/fullsdk model classifications
* Generate full SDK for CI using models in aws-sdk-rust
* Move the changelog renderer out of `sdk-lints` and add changelog splitter
* Save revision information into split off SDK changelog
* Replace common git impl with `sdk-sync`'s impl
* Filter SDK changelog entries on changelog render
* Add smithy-rs release workflow
* Add initial next SDK changelog
* Update `sdk-sync` to understand new models location

diff --git a/tools/ci-build/scripts/generate-aws-sdk b/tools/ci-build/scripts/generate-aws-sdk
--- a/tools/ci-build/scripts/generate-aws-sdk
+++ b/tools/ci-build/scripts/generate-aws-sdk
@@ -8,11 +8,17 @@ C_YELLOW='\033[1;33m'
 C_RESET='\033[0m'
 set -eux
 
-# This script takes an optional argument to specify the path to the previous release's versions.toml file
-PREVIOUS_RELEASE_VERSIONS_ARG=
-if [[ $# -ge 1 ]]; then
-    echo "Given previous release manifest path: $1"
-    PREVIOUS_RELEASE_VERSIONS_ARG="-Paws.sdk.previous.release.versions.manifest=$1"
+PREVIOUS_RELEASE_VERSIONS_ARG="$(pwd)/aws-sdk-rust/versions.toml"
+if [[ ! -f "${PREVIOUS_RELEASE_VERSIONS_ARG}" ]]; then
+    echo "Failed to find versions.toml file at ${PREVIOUS_RELEASE_VERSIONS_ARG}"
+    exit 1
+fi
+
+echo -e "${C_YELLOW}Taking models from 'awslabs/aws-sdk-rust'...${C_RESET}"
+AWS_SDK_MODELS_PATH="$(pwd)/aws-sdk-rust/aws-models"
+if [[ ! -d "${AWS_SDK_MODELS_PATH}" ]]; then
+  echo "Failed to find AWS models in ${AWS_SDK_MODELS_PATH}"
+  exit 1
 fi
 
 echo -e "${C_YELLOW}Taking examples from 'awsdocs/aws-doc-sdk-examples'...${C_RESET}"
@@ -24,11 +30,9 @@ rm smithy-rs/aws/sdk/examples/Cargo.toml
 echo -e "${C_YELLOW}Generating services...${C_RESET}"
 cd smithy-rs
 
-# Intentionally not quoting PREVIOUS_RELEASE_VERSIONS_ARG so that if it has no value, it doesn't confuse gradle
-# shellcheck disable=SC2086
 ./gradlew \
-    -Paws.fullsdk=true \
+    -Paws.sdk.models.path="${AWS_SDK_MODELS_PATH}" \
     -Paws.sdk.examples.revision="${examples_revision}" \
-    ${PREVIOUS_RELEASE_VERSIONS_ARG} \
+    -Paws.sdk.previous.release.versions.manifest="${PREVIOUS_RELEASE_VERSIONS_ARG}" \
     aws:sdk:assemble
 mv aws/sdk/build/aws-sdk ../artifacts/
