fix GitHub script

diff --git a/tools/ci-scripts/check-semver b/tools/ci-scripts/check-semver
--- a/tools/ci-scripts/check-semver
+++ b/tools/ci-scripts/check-semver
@@ -7,12 +7,18 @@
 set -eux
 cd smithy-rs
 
-if [[ $# -ne 1 ]]; then
-    echo "Usage: check-semver <base-revision>"
+if [[ $# -gt 2 ]]; then
+    echo "Usage: check-semver <base-revision> <warn-on-failure (true/false)>"
     exit 1
 fi
 
 # Override version commit hash to prevent unnecessary diffs
 export SMITHY_RS_VERSION_COMMIT_HASH_OVERRIDE=ci
 base_revision="$1"
-./tools/ci-scripts/codegen-diff/semver-checks.py . "${base_revision}"
+warn_on_failure="$2"
+if [[ $warn_on_failure == "true" ]]
+then
+  ./tools/ci-scripts/codegen-diff/semver-checks.py . "${base_revision}" || echo "allowing failure"
+else
+  ./tools/ci-scripts/codegen-diff/semver-checks.py . "${base_revision}"
+fi
