generate and check rust-version for Smithy packages
Previously to this CR, many Smithy packages did not declare their MSRV.
This causes problems because the Cargo MSRV-aware resolver is by design
not fully backtracking.

For example, the current version of aws-config (1.8.10) depends on
aws-sdk-sts 1.90.0, which has a pretty high MSRV (1.88). Because of how
the MSRV-aware resolver works, as long as aws-config does not declare an
MSRV, everyone using rustc < 1.88 with an `aws-config = "1"` dependency
will pick aws-config 1.8.10 (because the resolver is eager), and then
fail to compile because all aws-sdk-sts versions that work with 1.8.10
don't work with rustc < 1.88.

This means that everyone using Smithy and updating their Cargo.lock had
to use rustc 1.88, which is quite annoying churn, especially for
libraries that want to have a fixed MSRV.

If aws-config 1.8.10 had a correctly-configured MSRV, then for example
cargo using rustc 1.87 would pick aws-config 1.8.9, which can use
aws-sdk-sts 1.89, which would keep working.

I don't think we should yank aws-config 1.8.10 as all users have already
updated their rustc, but this will prevent this problem from happening
during the next MSRV bump.

diff --git a/tools/ci-scripts/check-rust-runtimes b/tools/ci-scripts/check-rust-runtimes
--- a/tools/ci-scripts/check-rust-runtimes
+++ b/tools/ci-scripts/check-rust-runtimes
@@ -4,6 +4,8 @@
 # SPDX-License-Identifier: Apache-2.0
 #
 
+
+C_RED='\033[1;31m'
 C_YELLOW='\033[1;33m'
 C_RESET='\033[0m'
 
@@ -15,6 +17,16 @@ cd smithy-rs
 
 echo -e "# ${C_YELLOW}Auditing runtime crate version numbers...${C_RESET}"
 runtime-versioner audit --no-fetch
+
+# Compute MSRV from channel, ignoring patch version
+MAIN_MSRV=$(sed -rn 's/channel = "(1[.][0-9]+)([.][0-9]+)?"/\1/p' rust-toolchain.toml)
+
+if [ -z "$MAIN_MSRV" ]; then
+    echo -e "# ${C_RED}Unable to detect MSRV in rust-toolchain.toml${C_RESET}"
+    exit 1
+else
+    echo -e "# ${C_YELLOW}MSRV is ${MAIN_MSRV}${C_RESET}"
+fi
 
 for runtime_path in \
     "rust-runtime" \
@@ -41,6 +53,14 @@ do
     cargo +"${RUST_NIGHTLY_VERSION}" minimal-versions check --direct --all-features
 
     for crate_path in *; do
+        if [[ -f "${crate_path}/Cargo.toml" ]]; then
+            # verify that the MSRV is the main MSRV
+            package_msrv=$(sed -rn 's/rust-version = "([^"]+)"/\1/p' "${crate_path}/Cargo.toml")
+            if [[ "${package_msrv}" != "${MAIN_MSRV}" ]]; then
+                echo -e "## ${C_RED}MSRV mismatch in ${crate_path} - toolchain MSRV is ${MAIN_MSRV}, crate MSRV is ${package_msrv}${C_RESET}"
+                exit 1
+            fi
+        fi
         if [[ -f "${crate_path}/external-types.toml" ]]; then
             # Skip `aws-config` since it has its own checks in `check-aws-config`
             if [[ "${crate_path}" != "aws-config" ]]; then
