Run the canary as part of CI

diff --git a/.github/workflows/ci-pr-forks.yml b/.github/workflows/ci-pr-forks.yml
--- a/.github/workflows/ci-pr-forks.yml
+++ b/.github/workflows/ci-pr-forks.yml
@@ -43,3 +43,13 @@ jobs:
     uses: ./.github/workflows/ci.yml
     with:
       run_sdk_examples: true
+
+  # This is always a failing job since forked repositories do not have necessary repository secrets
+  # to run the canary. Thus, this job itself should not be required for merging.
+  canary:
+    name: Canary
+    if: ${{ github.event.pull_request.head.repo.full_name != 'smithy-lang/smithy-rs' }}
+    runs-on: ubuntu-latest
+    run: |
+      echo "Canary cannot be invoked from a forked repository. Ask a maintainer to manually invoke it using your PR."
+      exit 1
