Indicate canary cannot run for forks

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -307,7 +307,7 @@ jobs:
   # Run the canary against generated SDKs
   canary:
     name: Canary
-    if: ${{ github.event.pull_request.head.repo.full_name == 'smithy-lang/smithy-rs' }}
+    if: ${{ inputs.run_canary }}
     needs: generate
     runs-on: smithy_ubuntu-latest_8-core
     permissions:
@@ -330,6 +330,17 @@ jobs:
       with:
         action: run-canary
         action-arguments: ${{ secrets.CANARY_STACK_CDK_OUTPUTS_BUCKET_NAME }} ${{ steps.creds.outputs.aws-access-key-id }} ${{ steps.creds.outputs.aws-secret-access-key }} ${{ steps.creds.outputs.aws-session-token }}
+
+  # This is always a failing job since forked repositories do not have necessary repository secrets
+  # to run the canary
+  ask-maintainer-to-run-canary:
+    if: ${{ !inputs.run_canary }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Ask maintainer to run the canary
+      run: |
+        echo "Canary cannot be invoked from a forked repository. Ask a maintainer to manually invoke it using your PR."
+        exit 1
 
   # This job is split out from the rest since it is not required to pass for merge
   check-sdk-examples:
